[tool.black]
line-length = 99
skip-numeric-underscore-normalization = "True"
target_version = ['py37']
include = '\.pyi?$'
exclude = '(\.git|\.pytest_cache|\.mypy_cache|\.tox|\.venv|build|dist|docs)'


[tool.isort]
line_length = 99
multi_line_output = 3
lines_after_imports = 2
default_section = "THIRDPARTY"
known_first_party = "neural_processes"
sections = "STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
